export function accountCopy(fa: boolean) {
  return {
    menuAria: fa ? 'منوی حساب کاربری' : 'Account menu',
    profile: fa ? 'پروفایل' : 'Profile',
    changeRequest: fa ? 'درخواست تغییر' : 'Change request',
    password: fa ? 'تغییر رمز' : 'Change password',
    edit: fa ? 'ویرایش' : 'Edit',
    logout: fa ? 'خروج' : 'Sign out',
    close: fa ? 'بستن' : 'Close',
    profileTitle: fa ? 'پروفایل عضو' : 'Member profile',
    profileHint: fa ? 'اطلاعات حساب شما در سامانه.' : 'Your account details in the system.',
    editTitle: fa ? 'ویرایش پروفایل' : 'Edit profile',
    editHint: fa ? 'نام، تلفن و ایمیل تماس را به‌روز کنید.' : 'Update your name, phone, and contact email.',
    passwordTitle: fa ? 'تغییر رمز عبور' : 'Change password',
    passwordHint: fa ? 'رمز فعلی را وارد کنید، سپس رمز جدید را تنظیم کنید.' : 'Enter your current password, then set a new one.',
    requestTitle: fa ? 'درخواست تغییر' : 'Change request',
    requestHint: fa
      ? 'تغییر نام کاربری یا موارد حساس را اینجا درخواست دهید تا ادمین بررسی کند.'
      : 'Request sensitive changes such as username so an admin can review them.',
    logoutTitle: fa ? 'خروج از حساب' : 'Sign out',
    logoutHint: fa ? 'با خروج، باید دوباره وارد شوید.' : 'You will need to sign in again.',
    username: fa ? 'نام کاربری' : 'Username',
    fullName: fa ? 'نام کامل' : 'Full name',
    phone: fa ? 'تلفن' : 'Phone',
    contactEmail: fa ? 'ایمیل تماس' : 'Contact email',
    personnelCode: fa ? 'کد پرسنلی' : 'Personnel code',
    loginEmail: fa ? 'ایمیل ورود' : 'Login email',
    projects: fa ? 'پروژه‌ها' : 'Projects',
    empty: fa ? 'ثبت نشده' : 'Not set',
    save: fa ? 'ذخیره' : 'Save',
    saving: fa ? 'در حال ذخیره...' : 'Saving...',
    saved: fa ? 'ذخیره شد.' : 'Saved.',
    submitRequest: fa ? 'ثبت درخواست' : 'Submit request',
    submitting: fa ? 'در حال ارسال...' : 'Submitting...',
    requestSent: fa ? 'درخواست ثبت شد و برای بررسی ادمین ارسال شد.' : 'Request submitted for admin review.',
    field: fa ? 'مورد درخواستی' : 'Requested field',
    requestedValue: fa ? 'مقدار جدید' : 'New value',
    note: fa ? 'توضیح' : 'Note',
    fieldUsername: fa ? 'نام کاربری' : 'Username',
    fieldFullName: fa ? 'نام کامل' : 'Full name',
    fieldPhone: fa ? 'تلفن' : 'Phone',
    fieldContactEmail: fa ? 'ایمیل تماس' : 'Contact email',
    fieldOther: fa ? 'سایر' : 'Other',
    currentPassword: fa ? 'رمز فعلی' : 'Current password',
    newPassword: fa ? 'رمز جدید' : 'New password',
    confirmPassword: fa ? 'تأیید رمز جدید' : 'Confirm new password',
    updatePassword: fa ? 'به‌روزرسانی رمز عبور' : 'Update password',
    passwordUpdated: fa ? 'رمز عبور با موفقیت به‌روزرسانی شد.' : 'Password updated.',
    passwordMismatch: fa ? 'رمزهای جدید یکسان نیستند.' : 'New passwords do not match.',
    passwordShort: fa ? 'رمز عبور باید حداقل 6 کاراکتر باشد.' : 'Password must be at least 6 characters.',
    wrongPassword: fa ? 'رمز فعلی نادرست است.' : 'Current password is incorrect.',
    mustLogin: fa ? 'باید وارد شده باشید.' : 'You must be signed in.',
    confirmLogout: fa ? 'خروج از حساب' : 'Sign out',
    cancel: fa ? 'انصراف' : 'Cancel',
    loadError: fa ? 'بارگذاری اطلاعات انجام نشد.' : 'Could not load account details.',
    positions: fa ? 'سمت‌ها' : 'Roles',
  }
}

export type AccountSection = 'profile' | 'edit' | 'password' | 'change-request' | 'logout'

export const ACCOUNT_PATHS: Record<AccountSection, string> = {
  profile: '/account/profile',
  edit: '/account/edit',
  password: '/account/password',
  'change-request': '/account/change-request',
  logout: '/account/logout',
}
