import type { AccountingDocument, ExpenseItem } from '@/features/finance/lib/expense-types'
import { formatInvoiceNumber, getInvoiceWeekday } from '@/features/finance/lib/invoice-weekday'
import { rialToToman, tomanAmountToPersianWords } from '@/features/finance/lib/persian-amount-words'
import type { ScheduleCalendar } from '@/features/schedule/lib/calendar-preference'
import { formatScheduleDate } from '@/features/schedule/lib/dates'

function escapeCsv(value: string | number | null | undefined): string {
  const s = value == null ? '' : String(value)
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`
  return s
}

function escapeHtml(value: string | number | null | undefined): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/** Build CSV content for expense document list (UTF-8 BOM for Excel/Persian). */
export function buildExpenseCsv(
  rows: AccountingDocument[],
  locale: 'fa' | 'en' = 'fa',
  calendar: ScheduleCalendar = 'jalali'
): string {
  const headers =
    locale === 'fa'
      ? [
          'شماره سند',
          'شماره فاکتور',
          'تأمین‌کننده',
          'تاریخ',
          'نوع هزینه',
          'مبلغ',
          'وضعیت',
          'شرح',
        ]
      : [
          'Document No',
          'Invoice No',
          'Supplier',
          'Date',
          'Cost Type',
          'Amount',
          'Status',
          'Description',
        ]

  const lines = [headers.map(escapeCsv).join(',')]
  for (const row of rows) {
    lines.push(
      [
        row.document_no,
        row.invoice_no,
        row.supplier_name,
        formatScheduleDate(row.document_date, calendar),
        row.cost_type,
        row.amount,
        row.status,
        row.description,
      ]
        .map(escapeCsv)
        .join(',')
    )
  }
  return `\uFEFF${lines.join('\n')}`
}

export interface BuildExpenseHtmlOptions {
  projectName?: string | null
}

function lineQty(item: ExpenseItem): number {
  return Number.isFinite(item.quantity) && item.quantity > 0 ? item.quantity : 1
}

/** Printable HTML matching classic Persian «فاکتور فروش» layout. */
export function buildExpenseDocumentHtml(
  doc: AccountingDocument,
  locale: 'fa' | 'en' = 'fa',
  calendar: ScheduleCalendar = 'jalali',
  options: BuildExpenseHtmlOptions = {}
): string {
  const isFa = locale === 'fa'
  const dir = isFa ? 'rtl' : 'ltr'
  const title = isFa ? 'فاکتور فروش' : 'Sales Invoice'
  const items = [...(doc.expense_items ?? [])].sort((a, b) => a.line_no - b.line_no)
  const displayDate = formatScheduleDate(doc.document_date, calendar)
  const weekday = getInvoiceWeekday(doc.document_date, isFa ? 'fa' : 'en')
  const totalToman = rialToToman(doc.amount)
  const amountWords = isFa
    ? tomanAmountToPersianWords(totalToman)
    : `${formatInvoiceNumber(totalToman, 'en')} Tomans`
  const invoiceNo = escapeHtml(doc.invoice_no || doc.document_no || '—')
  const projectName = escapeHtml(options.projectName || '—')
  const supplier = escapeHtml(doc.supplier_name || '')

  const labels = isFa
    ? {
        invoiceNo: 'شماره فاکتور',
        date: 'تاریخ',
        day: 'روز',
        buyer: 'خریدار',
        project: 'پروژه',
        phone: 'شماره تماس',
        seller: 'فروشنده',
        row: 'ردیف',
        desc: 'شرح کالا',
        unit: 'واحد',
        qty: 'تعداد',
        unitPrice: 'فی (تومان)',
        multiply: 'ضرب',
        lineTotal: 'مبلغ کل (تومان)',
        grandTotal: 'جمع کل',
        amountWords: 'مبلغ به حروف',
        sellerSign: 'امضاء فروشنده',
        sellerStamp: 'مهر و امضاء فروشنده',
        buyerSign: 'امضاء خریدار',
        disclaimer:
          'کالاهای فوق سالم تحویل گردید و خریدار از نظر تعداد و قیمت تأیید می‌نماید.',
        noLines: 'ردیفی ثبت نشده است.',
        footer: 'تولیدشده توسط MSA',
      }
    : {
        invoiceNo: 'Invoice No.',
        date: 'Date',
        day: 'Day',
        buyer: 'Buyer',
        project: 'Project',
        phone: 'Phone',
        seller: 'Seller',
        row: '#',
        desc: 'Description',
        unit: 'Unit',
        qty: 'Qty',
        unitPrice: 'Unit price (Toman)',
        multiply: 'Calc',
        lineTotal: 'Line total (Toman)',
        grandTotal: 'Grand total',
        amountWords: 'Amount in words',
        sellerSign: 'Seller signature',
        sellerStamp: 'Seller stamp & signature',
        buyerSign: 'Buyer signature',
        disclaimer:
          'Goods delivered in good condition; buyer has verified quantities and prices.',
        noLines: 'No line items.',
        footer: 'Generated by MSA',
      }

  const rowsHtml =
    items.length === 0
      ? `<tr><td colspan="7">${labels.noLines}</td></tr>`
      : items
          .map((item, idx) => {
            const qty = lineQty(item)
            const unitToman = rialToToman(item.unit_price)
            const lineToman = rialToToman(item.amount)
            const calc = `${formatInvoiceNumber(qty, locale)} × ${formatInvoiceNumber(unitToman, locale)}`
            return `<tr>
          <td>${item.line_no || idx + 1}</td>
          <td class="desc">${escapeHtml(item.description || '—')}</td>
          <td>${escapeHtml(item.unit || '—')}</td>
          <td>${formatInvoiceNumber(qty, locale)}</td>
          <td>${formatInvoiceNumber(unitToman, locale)}</td>
          <td class="calc">${calc}</td>
          <td>${formatInvoiceNumber(lineToman, locale)}</td>
        </tr>`
          })
          .join('')

  return `<!DOCTYPE html>
<html lang="${isFa ? 'fa' : 'en'}" dir="${dir}">
<head>
  <meta charset="utf-8" />
  <title>${title} ${invoiceNo}</title>
  <style>
    @page { size: A4; margin: 12mm; }
    * { box-sizing: border-box; }
    body {
      font-family: Tahoma, "Segoe UI", Arial, sans-serif;
      color: #111;
      margin: 0;
      padding: 16px;
      font-size: 12px;
    }
    .sheet { max-width: 210mm; margin: 0 auto; border: 1px solid #222; padding: 18px 20px; }
    h1 { font-size: 22px; margin: 0 0 16px; text-align: center; letter-spacing: 0.02em; }
    .header {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 12px 24px;
      margin-bottom: 16px;
    }
    .field { display: flex; gap: 6px; margin: 4px 0; align-items: baseline; }
    .field strong { white-space: nowrap; }
    .field .line {
      flex: 1;
      border-bottom: 1px dotted #666;
      min-height: 1.2em;
      padding: 0 4px;
    }
    table { width: 100%; border-collapse: collapse; margin-top: 4px; }
    th, td {
      border: 1px solid #222;
      padding: 6px 4px;
      text-align: center;
      vertical-align: middle;
    }
    th { background: #f0f0f0; font-weight: 700; }
    td.desc { text-align: ${isFa ? 'right' : 'left'}; }
    td.calc { font-size: 10px; white-space: nowrap; }
    .total-label { text-align: ${isFa ? 'right' : 'left'}; font-weight: 700; background: #f7f7f7; }
    .words {
      border: 1px solid #222;
      padding: 8px 10px;
      margin-top: 10px;
    }
    .words strong { margin-inline-end: 6px; }
    .signs {
      display: grid;
      grid-template-columns: 1fr 1fr 1fr;
      gap: 12px;
      margin-top: 28px;
      text-align: center;
      font-size: 11px;
    }
    .sign-box { min-height: 72px; display: flex; flex-direction: column; justify-content: flex-end; }
    .sign-line { border-top: 1px solid #222; padding-top: 6px; }
    .stamp {
      width: 110px;
      height: 56px;
      margin: 0 auto 8px;
      border: 2px solid #0284c7;
      border-radius: 4px;
    }
    .disclaimer { margin-top: 14px; font-size: 10px; color: #444; line-height: 1.5; }
    .footer { margin-top: 10px; font-size: 9px; color: #888; text-align: center; }
    @media print {
      body { padding: 0; }
      .sheet { border: none; padding: 0; }
    }
  </style>
</head>
<body>
  <div class="sheet">
    <h1>${title}</h1>
    <div class="header">
      <div>
        <div class="field"><strong>${labels.invoiceNo}:</strong><span class="line">${invoiceNo}</span></div>
        <div class="field"><strong>${labels.date}:</strong><span class="line">${escapeHtml(displayDate)}</span></div>
        <div class="field"><strong>${labels.day}:</strong><span class="line">${escapeHtml(weekday)}</span></div>
        ${
          supplier
            ? `<div class="field"><strong>${labels.seller}:</strong><span class="line">${supplier}</span></div>`
            : ''
        }
      </div>
      <div>
        <div class="field"><strong>${labels.buyer}:</strong><span class="line"></span></div>
        <div class="field"><strong>${labels.project}:</strong><span class="line">${projectName}</span></div>
        <div class="field"><strong>${labels.phone}:</strong><span class="line"></span></div>
      </div>
    </div>
    <table>
      <thead>
        <tr>
          <th>${labels.row}</th>
          <th>${labels.desc}</th>
          <th>${labels.unit}</th>
          <th>${labels.qty}</th>
          <th>${labels.unitPrice}</th>
          <th>${labels.multiply}</th>
          <th>${labels.lineTotal}</th>
        </tr>
      </thead>
      <tbody>
        ${rowsHtml}
        <tr>
          <td colspan="6" class="total-label">${labels.grandTotal}</td>
          <td><strong>${formatInvoiceNumber(totalToman, locale)}</strong></td>
        </tr>
      </tbody>
    </table>
    <div class="words"><strong>${labels.amountWords}:</strong> ${escapeHtml(amountWords)}</div>
    <div class="signs">
      <div class="sign-box"><div class="sign-line">${labels.sellerSign}</div></div>
      <div class="sign-box">
        <div class="stamp"></div>
        <div>${labels.sellerStamp}</div>
      </div>
      <div class="sign-box"><div class="sign-line">${labels.buyerSign}</div></div>
    </div>
    <p class="disclaimer">${labels.disclaimer}</p>
    <div class="footer">${labels.footer}</div>
  </div>
</body>
</html>`
}

export function downloadTextFile(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.rel = 'noopener'
  a.style.display = 'none'
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1500)
}

export function openPrintableHtml(html: string) {
  const w = window.open('', '_blank')
  if (!w) return
  w.document.write(html)
  w.document.close()
  w.focus()
  setTimeout(() => {
    w.print()
  }, 250)
}

/** Parse simple CSV (comma-separated, supports quoted fields). */
export function parseCsvText(text: string): string[][] {
  const normalized = text.replace(/^\uFEFF/, '')
  const rows: string[][] = []
  let current: string[] = []
  let cell = ''
  let inQuotes = false

  for (let i = 0; i < normalized.length; i++) {
    const ch = normalized[i]
    if (inQuotes) {
      if (ch === '"') {
        if (normalized[i + 1] === '"') {
          cell += '"'
          i++
        } else {
          inQuotes = false
        }
      } else {
        cell += ch
      }
      continue
    }
    if (ch === '"') {
      inQuotes = true
      continue
    }
    if (ch === ',') {
      current.push(cell.trim())
      cell = ''
      continue
    }
    if (ch === '\n') {
      current.push(cell.trim())
      cell = ''
      if (current.some((c) => c.length > 0)) rows.push(current)
      current = []
      continue
    }
    if (ch === '\r') continue
    cell += ch
  }
  current.push(cell.trim())
  if (current.some((c) => c.length > 0)) rows.push(current)
  return rows
}
