import type {
  AlertLogEntry,
  AlertRouting,
  HseCamera,
  HseContractor,
  HseIncident,
  HseProject,
  HseRule,
  HseUser,
  HseZone,
  OverviewKpis,
  Severity,
} from '@/lib/hse/types'

/** Anchor day for relative demo timestamps. */
const T = (offsetHours: number, minute = 0): string => {
  const d = new Date(Date.UTC(2026, 7, 9, 12, 0, 0)) // 2026-08-09T12:00:00Z
  d.setUTCHours(d.getUTCHours() + offsetHours, minute, 0, 0)
  return d.toISOString()
}

export const HSE_PROJECT: HseProject = {
  id: 'proj-nht-p2',
  name: 'برج بندر شمالی — فاز ۲',
  code: 'NHT-P2',
  location: 'تورنتو، کنار آب',
}

export const HSE_USERS: HseUser[] = [
  {
    id: 'user-employer',
    name: 'النا رضایی',
    role: 'employer',
    email: 'کارفرما@نمونه.ایران',
  },
  {
    id: 'user-hse',
    name: 'جمشید احمدی',
    role: 'hse_officer',
    email: 'ایمنی@نمونه.ایران',
  },
  {
    id: 'user-tech',
    name: 'پریا نوری',
    role: 'technical_admin',
    email: 'فنی@نمونه.ایران',
  },
  {
    id: 'user-supervisor',
    name: 'مرتضی بل',
    role: 'supervisor',
    email: 'ناظر@نمونه.ایران',
  },
]

export const HSE_CONTRACTORS: HseContractor[] = [
  {
    id: 'ctr-01',
    name: 'سازه سامیت',
    trade: 'فولاد سازه و عرشه',
    openIncidents: 5,
    confirmedViolations: 11,
    falsePositives: 3,
  },
  {
    id: 'ctr-02',
    name: 'تأسیسات لیک‌ویو',
    trade: 'مکانیک / برق',
    openIncidents: 3,
    confirmedViolations: 7,
    falsePositives: 2,
  },
  {
    id: 'ctr-03',
    name: 'بتن هاربرفرم',
    trade: 'قالب‌بندی و بتن',
    openIncidents: 4,
    confirmedViolations: 9,
    falsePositives: 4,
  },
  {
    id: 'ctr-04',
    name: 'دسترسی اسکای‌لاین',
    trade: 'داربست و سکوی معلق',
    openIncidents: 2,
    confirmedViolations: 5,
    falsePositives: 1,
  },
]

export const HSE_CAMERAS: HseCamera[] = [
  {
    id: 'cam-01',
    name: 'جرثقیل برجی غرب — نمای بوم',
    code: 'CAM-TCW-01',
    health: 'online',
    sourceType: 'rtsp',
    location: 'جرثقیل غرب، نوک طبقه ۱۸',
    lastHeartbeat: T(-0.2, 12),
    zoneIds: ['zone-01', 'zone-02'],
    fps: 15,
    resolution: '2560x1440',
    calibration: {
      tiltDeg: -28,
      panDeg: 142,
      zoom: 1.4,
      roiNotes: 'دایره ممنوع زیر مسیر بار؛ خود نوک بوم را نادیده بگیرید',
    },
  },
  {
    id: 'cam-02',
    name: 'راهروی هسته لابی — پله ب',
    code: 'CAM-LSB-02',
    health: 'online',
    sourceType: 'onvif',
    location: 'هسته ساختمان، پله ب طبقات ۱۲ تا ۱۴',
    lastHeartbeat: T(-0.1, 48),
    zoneIds: ['zone-03'],
    fps: 12,
    resolution: '1920x1080',
    calibration: {
      tiltDeg: -12,
      panDeg: 8,
      zoom: 1.0,
      roiNotes: 'پوشش کامل پاگرد؛ ناحیه مورد نظر کلاه‌ایمنی روی نوار سر',
    },
  },
  {
    id: 'cam-03',
    name: 'خلیج کار گرم سکو',
    code: 'CAM-PHW-03',
    health: 'degraded',
    sourceType: 'nvr',
    location: 'سکو طبقه ۳، پد جوشکاری خلیج ۴',
    lastHeartbeat: T(-0.8, 5),
    zoneIds: ['zone-04'],
    fps: 10,
    resolution: '1920x1080',
    calibration: {
      tiltDeg: -18,
      panDeg: -35,
      zoom: 1.2,
      roiNotes: 'ستون جرقه + ناحیه همپوشانی تابلوی مجوز',
    },
  },
  {
    id: 'cam-04',
    name: 'دروازه اسکله بارگیری الف',
    code: 'CAM-LDA-04',
    health: 'online',
    sourceType: 'rtsp',
    location: 'همکف دروازه الف، آپرون کامیون',
    lastHeartbeat: T(-0.15, 22),
    zoneIds: ['zone-05'],
    fps: 20,
    resolution: '2560x1440',
    calibration: {
      tiltDeg: -22,
      panDeg: 90,
      zoom: 1.1,
      roiNotes: 'راهروی نزدیکی خودرو + نوار عبور عابر',
    },
  },
  {
    id: 'cam-05',
    name: 'لبه عرشه — دیوار پرده‌ای شمال',
    code: 'CAM-EDN-05',
    health: 'calibrating',
    sourceType: 'edge_usb',
    location: 'طبقه ۲۲ لبه شمال، دکل موقت',
    lastHeartbeat: T(-1.5, 0),
    zoneIds: ['zone-01', 'zone-06'],
    fps: 8,
    resolution: '1280x720',
    calibration: {
      tiltDeg: -40,
      panDeg: 0,
      zoom: 0.9,
      roiNotes: 'خط لبه خطر سقوط پس از جابه‌جایی دکل در حال کالیبره مجدد',
    },
  },
  {
    id: 'cam-06',
    name: 'نماى داربست — وجه جنوب',
    code: 'CAM-SES-06',
    health: 'online',
    sourceType: 'onvif',
    location: 'داربست نمای جنوب طبقات ۸ تا ۱۱',
    lastHeartbeat: T(-0.3, 40),
    zoneIds: ['zone-06'],
    fps: 12,
    resolution: '1920x1080',
    calibration: {
      tiltDeg: -8,
      panDeg: 180,
      zoom: 1.3,
      roiNotes: 'شبکه کامل بودن نرده؛ فاصله نرده میانی پرچم می‌شود',
    },
  },
  {
    id: 'cam-07',
    name: 'سکوی بالابر مصالح',
    code: 'CAM-MHP-07',
    health: 'offline',
    sourceType: 'nvr',
    location: 'بالابر ۲، پاگرد طبقه ۹',
    lastHeartbeat: T(-14, 10),
    zoneIds: ['zone-02', 'zone-05'],
    fps: 0,
    resolution: '1920x1080',
    calibration: {
      tiltDeg: -15,
      panDeg: 45,
      zoom: 1.0,
      roiNotes: 'آخرین ناحیه مورد نظر شناخته‌شده پیش از قطع کانال ضبط‌کننده شبکه',
    },
  },
  {
    id: 'cam-08',
    name: 'کنترل سیگار — ورودی کارگاه',
    code: 'CAM-SCE-08',
    health: 'online',
    sourceType: 'rtsp',
    location: 'میدان گیت اصلی، سایبان غرب',
    lastHeartbeat: T(-0.05, 3),
    zoneIds: ['zone-03'],
    fps: 15,
    resolution: '1920x1080',
    calibration: {
      tiltDeg: -10,
      panDeg: -12,
      zoom: 1.5,
      roiNotes: 'زون ممنوع سیگار زیر سایبان؛ پیاده‌رو خیابان را نادیده بگیرید',
    },
  },
]

export const HSE_ZONES: HseZone[] = [
  {
    id: 'zone-01',
    name: 'زون سقوط بار جرثقیل',
    code: 'Z-CLD',
    risk: 'critical',
    cameraIds: ['cam-01', 'cam-05'],
    ruleIds: ['rule-03', 'rule-05'],
    notes: 'فعال هنگام بلند کردن فولاد ۰۶:۰۰ تا ۱۸:۰۰. داخل حلقه رنگ‌شده نیاز به ناظر بار است.',
    areaLabel: 'ردپای برج غرب طبقات ۱۶ تا ۲۰',
  },
  {
    id: 'zone-02',
    name: 'لبه عرشه — شمال',
    code: 'Z-DEN',
    risk: 'critical',
    cameraIds: ['cam-01', 'cam-07'],
    ruleIds: ['rule-04', 'rule-01'],
    notes: 'حفاظ لبه تا نصب پنل دیوار پرده‌ای ناقص است. بررسی بند مهار اجباری است.',
    areaLabel: 'لبه دال شمال طبقات ۱۸ تا ۲۲',
  },
  {
    id: 'zone-03',
    name: 'گردش هسته و دروازه تجهیزات حفاظت فردی',
    code: 'Z-CCG',
    risk: 'high',
    cameraIds: ['cam-02', 'cam-08'],
    ruleIds: ['rule-01', 'rule-02', 'rule-08'],
    notes: 'ایست بازرسی اصلی تجهیزات حفاظت فردی برای ورود از سکو. کلاه نرم پذیرفته نیست.',
    areaLabel: 'پله ب + میدان ورودی اصلی',
  },
  {
    id: 'zone-04',
    name: 'پد مجوز کار گرم',
    code: 'Z-HWP',
    risk: 'high',
    cameraIds: ['cam-03'],
    ruleIds: ['rule-06'],
    notes: 'تابلوی مجوز باید دیده شود. نگهبان آتش ۳۰ دقیقه پس از آخرین جوش انتظار می‌رود.',
    areaLabel: 'سکو طبقه ۳ خلیج ۴',
  },
  {
    id: 'zone-05',
    name: 'راهروی تعامل خودرو',
    code: 'Z-VIC',
    risk: 'high',
    cameraIds: ['cam-04', 'cam-07'],
    ruleIds: ['rule-05'],
    notes: 'آپرون مشترک پمپ بتن و کامیون تحویل. راه عابر باید خالی بماند.',
    areaLabel: 'آپرون کامیون دروازه الف',
  },
  {
    id: 'zone-06',
    name: 'نماى داربست جنوب',
    code: 'Z-SSE',
    risk: 'medium',
    cameraIds: ['cam-05', 'cam-06'],
    ruleIds: ['rule-07', 'rule-04'],
    notes: 'بازرسی روزانه برچسب داربست. سکوهای ناقص پیش از ورود تیم پرچم می‌شوند.',
    areaLabel: 'وجه جنوب طبقات ۸ تا ۱۱',
  },
]

export const HSE_RULES: HseRule[] = [
  {
    id: 'rule-01',
    name: 'نبود تجهیزات حفاظت فردی',
    code: 'R-PPE',
    severity: 'high',
    confidenceThreshold: 0.82,
    durationThresholdSec: 4,
    cooldownSec: 120,
    zoneIds: ['zone-02', 'zone-03'],
    enabled: true,
    description:
      'کارگران بدون جلیقه بازتابی یا عینک ایمنی لازم در زون‌های کاری فعال را تشخیص می‌دهد.',
    category: 'تجهیزات حفاظت فردی',
  },
  {
    id: 'rule-02',
    name: 'بدون کلاه‌ایمنی',
    code: 'R-HAT',
    severity: 'high',
    confidenceThreshold: 0.85,
    durationThresholdSec: 3,
    cooldownSec: 90,
    zoneIds: ['zone-03'],
    enabled: true,
    description: 'افراد بدون کلاه‌ایمنی در مناطق اجباری حفاظت سر را پرچم می‌کند.',
    category: 'تجهیزات حفاظت فردی',
  },
  {
    id: 'rule-03',
    name: 'نقض زون ممنوع',
    code: 'R-EXZ',
    severity: 'critical',
    confidenceThreshold: 0.78,
    durationThresholdSec: 2,
    cooldownSec: 60,
    zoneIds: ['zone-01'],
    enabled: true,
    description: 'فرد هنگام بلند کردن فعال وارد دایره سقوط بار جرثقیل می‌شود.',
    category: 'ممنوع',
  },
  {
    id: 'rule-04',
    name: 'خطر سقوط — مواجهه لبه',
    code: 'R-FALL',
    severity: 'critical',
    confidenceThreshold: 0.8,
    durationThresholdSec: 3,
    cooldownSec: 90,
    zoneIds: ['zone-02', 'zone-06'],
    enabled: true,
    description: 'کارگر در فاصله ۲ متری لبه بدون حفاظ قابل‌رؤیت مهار / بند.',
    category: 'حفاظت از سقوط',
  },
  {
    id: 'rule-05',
    name: 'نزدیکی خودرو',
    code: 'R-VEH',
    severity: 'critical',
    confidenceThreshold: 0.75,
    durationThresholdSec: 2,
    cooldownSec: 45,
    zoneIds: ['zone-01', 'zone-05'],
    enabled: true,
    description: 'عابر در شعاع خطر ماشین‌آلات متحرک یا خودروی تحویل.',
    category: 'ماشین‌آلات و خودرو',
  },
  {
    id: 'rule-06',
    name: 'کار گرم بدون مجوز',
    code: 'R-HOT',
    severity: 'high',
    confidenceThreshold: 0.77,
    durationThresholdSec: 8,
    cooldownSec: 300,
    zoneIds: ['zone-04'],
    enabled: true,
    description: 'فعالیت جوش یا برش وقتی تابلوی مجوز غایب یا منقضی است.',
    category: 'کار گرم',
  },
  {
    id: 'rule-07',
    name: 'داربست ناقص',
    code: 'R-SCA',
    severity: 'medium',
    confidenceThreshold: 0.8,
    durationThresholdSec: 10,
    cooldownSec: 600,
    zoneIds: ['zone-06'],
    enabled: true,
    description: 'نبود نرده، تخته پا یا ناقص بودن تخته‌های سکو روی داربست برچسب‌خورده.',
    category: 'داربست',
  },
  {
    id: 'rule-08',
    name: 'سیگار در منطقه ممنوع',
    code: 'R-SMK',
    severity: 'medium',
    confidenceThreshold: 0.72,
    durationThresholdSec: 5,
    cooldownSec: 180,
    zoneIds: ['zone-03'],
    enabled: true,
    description: 'سیگار یا شعله باز داخل زون ممنوع ورودی کارگاه.',
    category: 'قوانین کارگاه',
  },
]

const CLIP = 'کلیپ ۱۵ ثانیه‌ای لبه — بافر محلی'

export const HSE_INCIDENTS: HseIncident[] = [
  {
    id: 'inc-001',
    code: 'INC-2026-0809-001',
    title: 'ورود کارگر به زون سقوط جرثقیل هنگام بلند کردن فولاد',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-01',
    cameraId: 'cam-01',
    ruleId: 'rule-03',
    contractorId: 'ctr-01',
    severity: 'critical',
    status: 'escalated',
    confidence: 0.91,
    detectedAt: T(-2, 8),
    updatedAt: T(-1, 40),
    assignee: 'جمشید احمدی',
    aiSummary:
      'فرد هنگام چرخش جرثقیل غربی با تیر، وارد حلقه رنگ‌شده بار شد. ناظر بار رو به جای دیگری بود؛ پیش از نقض، سیگنال توقف دیده نشد.',
    aiVerdict: 'likely_violation',
    aiConfidence: 0.93,
    evidenceFrames: [
      {
        id: 'ef-001-a',
        label: 'فریم الف',
        timestamp: T(-2, 8),
        caption: 'حلقه بار خالی؛ بوم جرثقیل به مسیر بلند کردن نزدیک می‌شود',
      },
      {
        id: 'ef-001-b',
        label: 'فریم ب',
        timestamp: T(-2, 8),
        caption: 'کارگر از حلقه زرد زیر بار معلق عبور می‌کند',
      },
      {
        id: 'ef-001-c',
        label: 'فریم ج',
        timestamp: T(-2, 9),
        caption: 'ناظر بار برمی‌گردد؛ کارگر هنوز داخل دایره ممنوع است',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-001-1',
        at: T(-2, 9),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'اطمینان مدل ۰٫۹۱؛ تله‌متری بلند کردن فعال بودن را تأیید کرد',
      },
      {
        id: 'dl-001-2',
        at: T(-1, 55),
        actor: 'مرتضی بل',
        action: 'acknowledge',
        note: 'بلند کردن متوقف شد؛ حلقه پاک‌سازی شد',
      },
      {
        id: 'dl-001-3',
        at: T(-1, 48),
        actor: 'جمشید احمدی',
        action: 'confirm',
        note: 'نقض ممنوع تأیید شد — جلسه ایمنی کوتاه لازم است',
      },
      {
        id: 'dl-001-4',
        at: T(-1, 40),
        actor: 'النا رضایی',
        action: 'escalate',
        note: 'به مدیر پیمانکار ارجاع شد؛ بلند کردن تا توجیه معلق است',
      },
    ],
    correctiveActions: [
      {
        id: 'ca-001-1',
        title: 'بازآموزی پروتکل ناظر بار برای بلند کردن جرثقیل غرب',
        owner: 'مرتضی بل',
        dueDate: '2026-08-10',
        status: 'in_progress',
      },
      {
        id: 'ca-001-2',
        title: 'افزودن دومین ناظر بار برای بلند کردن همزمان',
        owner: 'سازه سامیت',
        dueDate: '2026-08-11',
        status: 'open',
      },
    ],
    falsePositive: false,
  },
  {
    id: 'inc-002',
    code: 'INC-2026-0809-002',
    title: 'کار در لبه بدون حفاظ قابل‌رؤیت مهار',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-02',
    cameraId: 'cam-01',
    ruleId: 'rule-04',
    contractorId: 'ctr-01',
    severity: 'critical',
    status: 'confirmed',
    confidence: 0.88,
    detectedAt: T(-5, 22),
    updatedAt: T(-3, 10),
    assignee: 'جمشید احمدی',
    aiSummary:
      'دو کارگر عرشه موقت را در حدود ۱٫۵ متری لبه دال شمال نصب کردند. برای کارگر پیشرو در بازه ۴۰ ثانیه‌ای مهار یا نقطه لنگر دیده نشد.',
    aiVerdict: 'likely_violation',
    aiConfidence: 0.86,
    evidenceFrames: [
      {
        id: 'ef-002-a',
        label: 'فریم الف',
        timestamp: T(-5, 22),
        caption: 'کارگر پیشرو کنار لبه دال زانو زده و تخته می‌گذارد',
      },
      {
        id: 'ef-002-b',
        label: 'فریم ب',
        timestamp: T(-5, 23),
        caption: 'بند مهار دیده نمی‌شود؛ کارگر دوم با ورق نزدیک می‌شود',
      },
      {
        id: 'ef-002-c',
        label: 'فریم ج',
        timestamp: T(-5, 24),
        caption: 'لبه هنوز باز است؛ مانع موقت هنوز نصب نشده',
      },
      {
        id: 'ef-002-d',
        label: 'فریم د',
        timestamp: T(-5, 25),
        caption: 'ناظر می‌رسد؛ کار متوقف می‌شود',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-002-1',
        at: T(-5, 23),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'قانون خطر سقوط فعال شد؛ اطمینان بالای آستانه',
      },
      {
        id: 'dl-002-2',
        at: T(-4, 50),
        actor: 'مرتضی بل',
        action: 'acknowledge',
        note: 'تیم متوقف شد؛ بررسی مهار در جریان است',
      },
      {
        id: 'dl-002-3',
        at: T(-3, 10),
        actor: 'جمشید احمدی',
        action: 'confirm',
        note: 'تأیید شد — نبود سامانه جلوگیری از سقوط برای کار لبه',
      },
    ],
    correctiveActions: [
      {
        id: 'ca-002-1',
        title: 'نصب نرده موقت لبه پیش از شیفت بعد',
        owner: 'دسترسی اسکای‌لاین',
        dueDate: '2026-08-09',
        status: 'done',
      },
    ],
    falsePositive: false,
  },
  {
    id: 'inc-003',
    code: 'INC-2026-0809-003',
    title: 'عابر خیلی نزدیک به کامیون بتن در حال دنده عقب',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-05',
    cameraId: 'cam-04',
    ruleId: 'rule-05',
    contractorId: 'ctr-03',
    severity: 'critical',
    status: 'assigned',
    confidence: 0.84,
    detectedAt: T(-1, 5),
    updatedAt: T(-0.5, 20),
    assignee: 'مرتضی بل',
    aiSummary:
      'کارگر از راه عابر رنگ‌شده وارد آپرون کامیون شد در حالی که میکسر بتن به سمت دروازه الف دنده عقب می‌رفت. فاصله پیش از توقف به زیر ۲ متر رسید.',
    aiVerdict: 'likely_violation',
    aiConfidence: 0.85,
    evidenceFrames: [
      {
        id: 'ef-003-a',
        label: 'فریم الف',
        timestamp: T(-1, 5),
        caption: 'میکسر در دنده عقب با چراغ کهربایی روشن',
      },
      {
        id: 'ef-003-b',
        label: 'فریم ب',
        timestamp: T(-1, 5),
        caption: 'عابر از راه عابر وارد آپرون می‌شود',
      },
      {
        id: 'ef-003-c',
        label: 'فریم ج',
        timestamp: T(-1, 6),
        caption: 'هشدار نزدیکی؛ چراغ ترمز کامیون',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-003-1',
        at: T(-1, 6),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'قانون نزدیکی خودرو؛ ردیابی دو شیء قفل شد',
      },
      {
        id: 'dl-003-2',
        at: T(-0.7, 0),
        actor: 'مرتضی بل',
        action: 'acknowledge',
        note: 'ناظر بار تردد پیاده را هدایت کرد',
      },
      {
        id: 'dl-003-3',
        at: T(-0.5, 20),
        actor: 'جمشید احمدی',
        action: 'assign',
        note: 'برای بازبینی هدایت دروازه به بل تخصیص شد',
      },
    ],
    correctiveActions: [
      {
        id: 'ca-003-1',
        title: 'جابه‌جایی ناظر دروازه الف در پنجره‌های بتن‌ریزی',
        owner: 'مرتضی بل',
        dueDate: '2026-08-10',
        status: 'open',
      },
    ],
    falsePositive: false,
  },
  {
    id: 'inc-004',
    code: 'INC-2026-0808-014',
    title: 'جوشکاری فعال با تابلوی مجوز کار گرم منقضی',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-04',
    cameraId: 'cam-03',
    ruleId: 'rule-06',
    contractorId: 'ctr-02',
    severity: 'high',
    status: 'ai_review',
    confidence: 0.79,
    detectedAt: T(-18, 30),
    updatedAt: T(-16, 0),
    assignee: 'جمشید احمدی',
    aiSummary:
      'جرقه قوس و فعالیت کلاه جوش در خلیج ۴ تشخیص داده شد. خواندن تابلوی مجوز تاریخ دیروز را نشان می‌دهد؛ نگهبان آتش در ۹۰ ثانیه اول در قاب نبود.',
    aiVerdict: 'uncertain',
    aiConfidence: 0.71,
    evidenceFrames: [
      {
        id: 'ef-004-a',
        label: 'فریم الف',
        timestamp: T(-18, 30),
        caption: 'جرقه قوس روی میز کار دیده می‌شود',
      },
      {
        id: 'ef-004-b',
        label: 'فریم ب',
        timestamp: T(-18, 31),
        caption: 'نمای نزدیک تابلوی مجوز — تاریخ ۲۰۲۶-۰۸-۰۸',
      },
      {
        id: 'ef-004-c',
        label: 'فریم ج',
        timestamp: T(-18, 32),
        caption: 'نگهبان آتش در جایگاه تعیین‌شده نیست',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-004-1',
        at: T(-18, 31),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'قانون کار گرم؛ اطمینان خواندن تاریخ مجوز متوسط است',
      },
      {
        id: 'dl-004-2',
        at: T(-16, 0),
        actor: 'جمشید احمدی',
        action: 'note',
        note: 'در انتظار تأیید عکس مجوز تمدیدشده از سرپرست تأسیسات',
      },
    ],
    correctiveActions: [],
    falsePositive: false,
  },
  {
    id: 'inc-005',
    code: 'INC-2026-0809-005',
    title: 'برداشتن کلاه‌ایمنی در پاگرد پله ب',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-03',
    cameraId: 'cam-02',
    ruleId: 'rule-02',
    contractorId: 'ctr-02',
    severity: 'high',
    status: 'acknowledged',
    confidence: 0.9,
    detectedAt: T(-0.8, 15),
    updatedAt: T(-0.6, 0),
    assignee: 'مرتضی بل',
    aiSummary:
      'برق‌کار هنگام چیدن قرقره‌های کابل در پاگرد طبقه ۱۳ کلاه‌ایمنی را برداشت و ۲۲ ثانیه بدون حفاظت سر ماند.',
    aiVerdict: 'likely_violation',
    aiConfidence: 0.92,
    evidenceFrames: [
      {
        id: 'ef-005-a',
        label: 'فریم الف',
        timestamp: T(-0.8, 15),
        caption: 'کلاه‌ایمنی برداشته و روی قرقره گذاشته شد',
      },
      {
        id: 'ef-005-b',
        label: 'فریم ب',
        timestamp: T(-0.8, 16),
        caption: 'کارگر بدون حفاظت سر به چیدن ادامه می‌دهد',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-005-1',
        at: T(-0.8, 16),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'نبود کلاه‌ایمنی از آستانه مدت عبور کرد',
      },
      {
        id: 'dl-005-2',
        at: T(-0.6, 0),
        actor: 'مرتضی بل',
        action: 'acknowledge',
        note: 'با سرپرست تیم صحبت شد؛ کلاه دوباره روی سر است',
      },
    ],
    correctiveActions: [],
    falsePositive: false,
  },
  {
    id: 'inc-006',
    code: 'INC-2026-0809-006',
    title: 'نبود جلیقه بازتابی در دروازه تجهیزات حفاظت فردی',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-03',
    cameraId: 'cam-08',
    ruleId: 'rule-01',
    contractorId: 'ctr-03',
    severity: 'high',
    status: 'new',
    confidence: 0.87,
    detectedAt: T(-0.25, 40),
    updatedAt: T(-0.25, 40),
    assignee: null,
    aiSummary:
      'کارگر قالب‌بندی با لباس تیره بدون جلیقه بازتابی از گیت اصلی گذشت. عینک داشت؛ جلیقه نداشت.',
    aiVerdict: 'likely_violation',
    aiConfidence: 0.88,
    evidenceFrames: [
      {
        id: 'ef-006-a',
        label: 'فریم الف',
        timestamp: T(-0.25, 40),
        caption: 'ورود از گیت بدون جلیقه بازتابی',
      },
      {
        id: 'ef-006-b',
        label: 'فریم ب',
        timestamp: T(-0.25, 41),
        caption: 'به سمت دسترسی پله ب ادامه می‌دهد',
      },
      {
        id: 'ef-006-c',
        label: 'فریم ج',
        timestamp: T(-0.25, 42),
        caption: 'متصدی دروازه به تبلت نگاه می‌کند',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-006-1',
        at: T(-0.25, 41),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'قانون نبود تجهیزات حفاظت فردی؛ طبقه‌بند جلیقه مثبت',
      },
    ],
    correctiveActions: [],
    falsePositive: false,
  },
  {
    id: 'inc-007',
    code: 'INC-2026-0808-021',
    title: 'فاصله نرده میانی داربست در نمای جنوب طبقه ۱۰',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-06',
    cameraId: 'cam-06',
    ruleId: 'rule-07',
    contractorId: 'ctr-04',
    severity: 'medium',
    status: 'confirmed',
    confidence: 0.83,
    detectedAt: T(-22, 0),
    updatedAt: T(-12, 30),
    assignee: 'جمشید احمدی',
    aiSummary:
      'دهانه داربست طبقه ۱۰ جنوب نرده میانی به طول تقریبی ۲٫۴ متر ندارد. تخته‌های سکو کامل‌اند؛ تخته پا موجود است.',
    aiVerdict: 'likely_violation',
    aiConfidence: 0.84,
    evidenceFrames: [
      {
        id: 'ef-007-a',
        label: 'فریم الف',
        timestamp: T(-22, 0),
        caption: 'نمای گسترده داربست جنوب طبقه ۱۰',
      },
      {
        id: 'ef-007-b',
        label: 'فریم ب',
        timestamp: T(-22, 1),
        caption: 'بزرگ‌نمایی روی بخش نرده میانی مفقود',
      },
      {
        id: 'ef-007-c',
        label: 'فریم ج',
        timestamp: T(-21, 50),
        caption: 'کارگر بدون توجه به فاصله از دهانه باز عبور می‌کند',
      },
      {
        id: 'ef-007-d',
        label: 'فریم د',
        timestamp: T(-12, 20),
        caption: 'پس از تأیید — برچسب «استفاده نشود»',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-007-1',
        at: T(-22, 1),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'قانون داربست ناقص؛ تطبیق هندسی نرده میانی',
      },
      {
        id: 'dl-007-2',
        at: T(-20, 0),
        actor: 'مرتضی بل',
        action: 'acknowledge',
        note: 'دهانه تا تعمیر اسکای‌لاین ایزوله شد',
      },
      {
        id: 'dl-007-3',
        at: T(-12, 30),
        actor: 'جمشید احمدی',
        action: 'confirm',
        note: 'داربست ناقص تأیید شد — برچسب قرمز',
      },
    ],
    correctiveActions: [
      {
        id: 'ca-007-1',
        title: 'تعویض نرده میانی و بازرسی مجدد برچسب داربست',
        owner: 'دسترسی اسکای‌لاین',
        dueDate: '2026-08-09',
        status: 'in_progress',
      },
    ],
    falsePositive: false,
  },
  {
    id: 'inc-008',
    code: 'INC-2026-0809-008',
    title: 'سیگار زیر سایبان ورودی',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-03',
    cameraId: 'cam-08',
    ruleId: 'rule-08',
    contractorId: 'ctr-03',
    severity: 'medium',
    status: 'dismissed',
    confidence: 0.68,
    detectedAt: T(-3, 45),
    updatedAt: T(-2, 50),
    assignee: 'جمشید احمدی',
    aiSummary:
      'ستون حرارت و حرکت دست به دهان زیر سایبان غرب تشخیص داده شد. بازبینی بعدی بخار سیگار الکترونیکی بازدیدکننده‌ای در حال خروج را نشان داد.',
    aiVerdict: 'likely_false_positive',
    aiConfidence: 0.62,
    evidenceFrames: [
      {
        id: 'ef-008-a',
        label: 'فریم الف',
        timestamp: T(-3, 45),
        caption: 'ستون دود نزدیک ستون سایبان',
      },
      {
        id: 'ef-008-b',
        label: 'فریم ب',
        timestamp: T(-3, 46),
        caption: 'فرد به سمت گیت خروجی برمی‌گردد',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-008-1',
        at: T(-3, 46),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'قانون سیگار — اطمینان زیر آستانه قوی',
      },
      {
        id: 'dl-008-2',
        at: T(-3, 10),
        actor: 'مرتضی بل',
        action: 'acknowledge',
        note: 'میدان بررسی شد — بازدیدکننده در حال خروج',
      },
      {
        id: 'dl-008-3',
        at: T(-2, 50),
        actor: 'جمشید احمدی',
        action: 'dismiss',
        note: 'به‌عنوان مثبت کاذب رد شد — خارج از نیروی کار',
      },
    ],
    correctiveActions: [],
    falsePositive: true,
  },
  {
    id: 'inc-009',
    code: 'INC-2026-0807-033',
    title: 'خطر سقوط نزدیک نرده ناقص لبه شمال',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-02',
    cameraId: 'cam-05',
    ruleId: 'rule-04',
    contractorId: 'ctr-01',
    severity: 'critical',
    status: 'closed',
    confidence: 0.86,
    detectedAt: T(-46, 0),
    updatedAt: T(-30, 0),
    assignee: 'جمشید احمدی',
    aiSummary:
      'نصاب دیوار پرده‌ای کنار بازشدگی پنل لبه کار کرد. مهار پوشیده بود اما بند حدود ۳۵ ثانیه به لنگر وصل نبود.',
    aiVerdict: 'likely_violation',
    aiConfidence: 0.81,
    evidenceFrames: [
      {
        id: 'ef-009-a',
        label: 'فریم الف',
        timestamp: T(-46, 0),
        caption: 'کارگر کنار بازشدگی پنل لبه',
      },
      {
        id: 'ef-009-b',
        label: 'فریم ب',
        timestamp: T(-46, 1),
        caption: 'بند مهار آزاد آویزان است، روی لنگر نیست',
      },
      {
        id: 'ef-009-c',
        label: 'فریم ج',
        timestamp: T(-45, 50),
        caption: 'مداخله ناظر؛ اتصال تکمیل شد',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-009-1',
        at: T(-46, 1),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'قانون خطر سقوط؛ مهار موجود، اتصال غایب',
      },
      {
        id: 'dl-009-2',
        at: T(-45, 30),
        actor: 'مرتضی بل',
        action: 'acknowledge',
        note: 'کار متوقف شد؛ دوباره به لنگر وصل شد',
      },
      {
        id: 'dl-009-3',
        at: T(-40, 0),
        actor: 'جمشید احمدی',
        action: 'confirm',
        note: 'نقض اتصال کامل تأیید شد',
      },
      {
        id: 'dl-009-4',
        at: T(-32, 0),
        actor: 'جمشید احمدی',
        action: 'note',
        note: 'بازآموزی تیم تکمیل شد',
      },
      {
        id: 'dl-009-5',
        at: T(-30, 0),
        actor: 'النا رضایی',
        action: 'close',
        note: 'اقدامات اصلاحی تأیید شد؛ بسته شد',
      },
    ],
    correctiveActions: [
      {
        id: 'ca-009-1',
        title: 'دوره یادآوری اتصال کامل برای تیم دیوار پرده‌ای',
        owner: 'سازه سامیت',
        dueDate: '2026-08-08',
        status: 'done',
      },
    ],
    falsePositive: false,
  },
  {
    id: 'inc-010',
    code: 'INC-2026-0809-010',
    title: 'نزدیکی ماشین‌آلات هنگام کمک با طناب هدایت جرثقیل',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-01',
    cameraId: 'cam-01',
    ruleId: 'rule-05',
    contractorId: 'ctr-01',
    severity: 'high',
    status: 'acknowledged',
    confidence: 0.76,
    detectedAt: T(-4, 10),
    updatedAt: T(-3, 55),
    assignee: 'مرتضی بل',
    aiSummary:
      'نگهدارنده طناب هدایت وارد بافر خودروی تله‌هندلر منتظر زیر مسیر بار شد. تله‌هندلر ساکن بود اما موتور روشن بود.',
    aiVerdict: 'uncertain',
    aiConfidence: 0.69,
    evidenceFrames: [
      {
        id: 'ef-010-a',
        label: 'فریم الف',
        timestamp: T(-4, 10),
        caption: 'تله‌هندلر نزدیک حلقه سقوط پارک شده',
      },
      {
        id: 'ef-010-b',
        label: 'فریم ب',
        timestamp: T(-4, 11),
        caption: 'نگهدارنده طناب وارد بافر ماشین‌آلات می‌شود',
      },
      {
        id: 'ef-010-c',
        label: 'فریم ج',
        timestamp: T(-4, 12),
        caption: 'اپراتور در کابین می‌ماند؛ آژیر دنده عقب نیست',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-010-1',
        at: T(-4, 11),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'نزدیکی خودرو با ماشین‌آلات ساکن — مرزی',
      },
      {
        id: 'dl-010-2',
        at: T(-3, 55),
        actor: 'مرتضی بل',
        action: 'acknowledge',
        note: 'در حال بررسی اعمال بافر به ماشین‌آلات پارک‌شده',
      },
    ],
    correctiveActions: [],
    falsePositive: false,
  },
  {
    id: 'inc-011',
    code: 'INC-2026-0808-028',
    title: 'نبود عینک ایمنی هنگام باز کردن قالب',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-03',
    cameraId: 'cam-02',
    ruleId: 'rule-01',
    contractorId: 'ctr-03',
    severity: 'medium',
    status: 'closed',
    confidence: 0.81,
    detectedAt: T(-28, 15),
    updatedAt: T(-20, 0),
    assignee: 'جمشید احمدی',
    aiSummary:
      'نجار قالب‌بندی بدون حفاظت چشم مهارها را باز می‌کرد در حالی که آوار از عرشه بالا می‌ریخت. کلاه‌ایمنی و جلیقه موجود بود.',
    aiVerdict: 'likely_violation',
    aiConfidence: 0.8,
    evidenceFrames: [
      {
        id: 'ef-011-a',
        label: 'فریم الف',
        timestamp: T(-28, 15),
        caption: 'کارگر روی وجه قالب بدون عینک',
      },
      {
        id: 'ef-011-b',
        label: 'فریم ب',
        timestamp: T(-28, 16),
        caption: 'ریزش آوار از عرشه بالا',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-011-1',
        at: T(-28, 16),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'نبود تجهیزات حفاظت فردی — کلاس حفاظت چشم',
      },
      {
        id: 'dl-011-2',
        at: T(-27, 0),
        actor: 'مرتضی بل',
        action: 'acknowledge',
        note: 'عینک یدکی از کیت دروازه داده شد',
      },
      {
        id: 'dl-011-3',
        at: T(-24, 0),
        actor: 'جمشید احمدی',
        action: 'confirm',
        note: 'شکاف تجهیزات حفاظت فردی هنگام باز کردن تأیید شد',
      },
      {
        id: 'dl-011-4',
        at: T(-20, 0),
        actor: 'جمشید احمدی',
        action: 'close',
        note: 'پس از یادآوری جلسه کوتاه بسته شد',
      },
    ],
    correctiveActions: [
      {
        id: 'ca-011-1',
        title: 'ذخیره عینک ایمنی یدکی در پاگرد پله ب',
        owner: 'مرتضی بل',
        dueDate: '2026-08-09',
        status: 'done',
      },
    ],
    falsePositive: false,
  },
  {
    id: 'inc-012',
    code: 'INC-2026-0809-012',
    title: 'شروع کار گرم پیش از رسیدن نگهبان آتش',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-04',
    cameraId: 'cam-03',
    ruleId: 'rule-06',
    contractorId: 'ctr-02',
    severity: 'high',
    status: 'confirmed',
    confidence: 0.85,
    detectedAt: T(-6, 40),
    updatedAt: T(-5, 5),
    assignee: 'جمشید احمدی',
    aiSummary:
      'حدود ۷۰ ثانیه جرقه سنگ‌زنی با تابلوی مجوز معتبر امروز، اما جایگاه نگهبان آتش خالی بود تا کارگر دوم با کپسول برسد.',
    aiVerdict: 'likely_violation',
    aiConfidence: 0.83,
    evidenceFrames: [
      {
        id: 'ef-012-a',
        label: 'فریم الف',
        timestamp: T(-6, 40),
        caption: 'جرقه سنگ‌زنی؛ تابلوی مجوز امروز معتبر است',
      },
      {
        id: 'ef-012-b',
        label: 'فریم ب',
        timestamp: T(-6, 41),
        caption: 'جایگاه نگهبان آتش خالی است',
      },
      {
        id: 'ef-012-c',
        label: 'فریم ج',
        timestamp: T(-6, 42),
        caption: 'نگهبان آتش با کپسول می‌رسد',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-012-1',
        at: T(-6, 41),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'کار گرم بدون نگهبان آتش در قاب',
      },
      {
        id: 'dl-012-2',
        at: T(-6, 10),
        actor: 'مرتضی بل',
        action: 'acknowledge',
        note: 'سنگ‌زنی تا حضور نگهبان متوقف شد',
      },
      {
        id: 'dl-012-3',
        at: T(-5, 5),
        actor: 'جمشید احمدی',
        action: 'confirm',
        note: 'تأیید شد — شرط مجوز در شروع رعایت نشد',
      },
    ],
    correctiveActions: [
      {
        id: 'ca-012-1',
        title: 'به‌روزرسانی چک‌لیست شروع خلیج ۴ — ابتدا نگهبان آتش',
        owner: 'تأسیسات لیک‌ویو',
        dueDate: '2026-08-10',
        status: 'open',
      },
    ],
    falsePositive: false,
  },
  {
    id: 'inc-013',
    code: 'INC-2026-0807-041',
    title: 'عبور از حلقه ممنوع هنگام حرکت قلاب خالی',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-01',
    cameraId: 'cam-01',
    ruleId: 'rule-03',
    contractorId: null,
    severity: 'low',
    status: 'dismissed',
    confidence: 0.74,
    detectedAt: T(-50, 20),
    updatedAt: T(-48, 0),
    assignee: 'جمشید احمدی',
    aiSummary:
      'فرد کوتاه وارد حلقه رنگ‌شده شد در حالی که قلاب جرثقیل خالی بین بلند کردن‌ها حرکت می‌کرد. رویه کارگاه عبور بدون بار معلق را مجاز می‌داند؛ هوش مصنوعی همچنان پرچم زد.',
    aiVerdict: 'likely_false_positive',
    aiConfidence: 0.77,
    evidenceFrames: [
      {
        id: 'ef-013-a',
        label: 'فریم الف',
        timestamp: T(-50, 20),
        caption: 'قلاب خالی در حرکت؛ بدون بار',
      },
      {
        id: 'ef-013-b',
        label: 'فریم ب',
        timestamp: T(-50, 21),
        caption: 'کارگر کوتاه از حلقه عبور می‌کند',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-013-1',
        at: T(-50, 21),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'نقض ممنوع با تله‌متری قلاب خالی',
      },
      {
        id: 'dl-013-2',
        at: T(-49, 0),
        actor: 'جمشید احمدی',
        action: 'acknowledge',
        note: 'گزارش بلند کردن بررسی شد — در آن زمان بار نبود',
      },
      {
        id: 'dl-013-3',
        at: T(-48, 0),
        actor: 'جمشید احمدی',
        action: 'dismiss',
        note: 'مثبت کاذب طبق قاعده عبور قلاب خالی',
      },
    ],
    correctiveActions: [],
    falsePositive: true,
  },
  {
    id: 'inc-014',
    code: 'INC-2026-0809-014',
    title: 'تخته‌های ناقص سکوی داربست طبقه ۹',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-06',
    cameraId: 'cam-06',
    ruleId: 'rule-07',
    contractorId: 'ctr-04',
    severity: 'medium',
    status: 'new',
    confidence: 0.8,
    detectedAt: T(-0.4, 5),
    updatedAt: T(-0.4, 5),
    assignee: null,
    aiSummary:
      'دو تخته سکو در دهانه جنوب طبقه ۹ پس از چیدن مصالح غایب است. دهانه به‌اندازه گیر کردن پا بزرگ است؛ فعلاً تیمی روی آن دهانه نیست.',
    aiVerdict: 'likely_violation',
    aiConfidence: 0.82,
    evidenceFrames: [
      {
        id: 'ef-014-a',
        label: 'فریم الف',
        timestamp: T(-0.4, 5),
        caption: 'فاصله در تخته‌های سکو طبقه ۹',
      },
      {
        id: 'ef-014-b',
        label: 'فریم ب',
        timestamp: T(-0.4, 6),
        caption: 'مصالح روی دهانه کامل مجاور چیده شده',
      },
      {
        id: 'ef-014-c',
        label: 'فریم ج',
        timestamp: T(-0.4, 7),
        caption: 'برچسب داربست هنوز سبز است — قدیمی',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-014-1',
        at: T(-0.4, 6),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'داربست ناقص — فاصله تخته تشخیص داده شد',
      },
    ],
    correctiveActions: [],
    falsePositive: false,
  },
  {
    id: 'inc-015',
    code: 'INC-2026-0808-036',
    title: 'نبود کلاه‌ایمنی هنگام تخلیه پاگرد بالابر',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-05',
    cameraId: 'cam-07',
    ruleId: 'rule-02',
    contractorId: 'ctr-02',
    severity: 'high',
    status: 'closed',
    confidence: 0.89,
    detectedAt: T(-26, 40),
    updatedAt: T(-19, 10),
    assignee: 'مرتضی بل',
    aiSummary:
      'کارگر تأسیسات لوله را از بالابر مصالح ۲ بدون کلاه‌ایمنی تخلیه کرد. حادثه پیش از قطع بعدی کانال ضبط‌کننده شبکه ثبت شد.',
    aiVerdict: 'likely_violation',
    aiConfidence: 0.9,
    evidenceFrames: [
      {
        id: 'ef-015-a',
        label: 'فریم الف',
        timestamp: T(-26, 40),
        caption: 'دروازه بالابر باز؛ کارگر بدون کلاه',
      },
      {
        id: 'ef-015-b',
        label: 'فریم ب',
        timestamp: T(-26, 41),
        caption: 'بسته لوله را به پاگرد می‌کشد',
      },
      {
        id: 'ef-015-c',
        label: 'فریم ج',
        timestamp: T(-26, 42),
        caption: 'کارگر دوم به نبود کلاه اشاره می‌کند',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-015-1',
        at: T(-26, 41),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'بدون کلاه‌ایمنی در پاگرد بالابر',
      },
      {
        id: 'dl-015-2',
        at: T(-26, 0),
        actor: 'مرتضی بل',
        action: 'acknowledge',
        note: 'کلاه از قفس برداشته شد',
      },
      {
        id: 'dl-015-3',
        at: T(-22, 0),
        actor: 'جمشید احمدی',
        action: 'confirm',
        note: 'نقض تجهیزات حفاظت فردی در بالابر ۲ تأیید شد',
      },
      {
        id: 'dl-015-4',
        at: T(-19, 10),
        actor: 'مرتضی بل',
        action: 'close',
        note: 'پس از ثبت اخطار شفاهی بسته شد',
      },
    ],
    correctiveActions: [],
    falsePositive: false,
  },
  {
    id: 'inc-016',
    code: 'INC-2026-0809-016',
    title: 'مواجهه لبه هنگام کالیبره مجدد دکل دوربین',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-06',
    cameraId: 'cam-05',
    ruleId: 'rule-04',
    contractorId: 'ctr-04',
    severity: 'critical',
    status: 'ai_review',
    confidence: 0.72,
    detectedAt: T(-1.2, 0),
    updatedAt: T(-1, 0),
    assignee: 'پریا نوری',
    aiSummary:
      'تکنسین در حال تنظیم دکل لبه طبقه ۲۲ داخل ناحیه مورد نظر خطر سقوط دیده شد. دوربین در حال کالیبره است؛ اطمینان هوش مصنوعی به‌خاطر هندسه در حال تغییر کاهش یافته.',
    aiVerdict: 'uncertain',
    aiConfidence: 0.58,
    evidenceFrames: [
      {
        id: 'ef-016-a',
        label: 'فریم الف',
        timestamp: T(-1.2, 0),
        caption: 'تکنسین کنار دکل نزدیک لبه دال',
      },
      {
        id: 'ef-016-b',
        label: 'فریم ب',
        timestamp: T(-1.2, 1),
        caption: 'مهار دیده می‌شود؛ ناحیه مورد نظر هنوز جابه‌جا می‌شود',
      },
      {
        id: 'ef-016-c',
        label: 'فریم ج',
        timestamp: T(-1.1, 30),
        caption: 'همپوشانی کالیبراسیون ناقص است',
      },
      {
        id: 'ef-016-d',
        label: 'فریم د',
        timestamp: T(-1, 0),
        caption: 'نگه‌داشته برای بازبینی انسانی — اطمینان پایین',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-016-1',
        at: T(-1.2, 1),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'خطر سقوط هنگام کالیبراسیون — رأی نامشخص',
      },
      {
        id: 'dl-016-2',
        at: T(-1, 0),
        actor: 'پریا نوری',
        action: 'note',
        note: 'مدیر فنی پس از جابه‌جایی دکل ناحیه مورد نظر را بررسی می‌کند',
      },
    ],
    correctiveActions: [],
    falsePositive: false,
  },
  {
    id: 'inc-017',
    code: 'INC-2026-0806-052',
    title: 'سیگار در میدان ممنوع — تأییدشده',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-03',
    cameraId: 'cam-08',
    ruleId: 'rule-08',
    contractorId: 'ctr-01',
    severity: 'medium',
    status: 'closed',
    confidence: 0.86,
    detectedAt: T(-70, 0),
    updatedAt: T(-60, 0),
    assignee: 'جمشید احمدی',
    aiSummary:
      'فیتتر فولاد بیش از یک دقیقه زیر سایبان غرب سیگار کشید. سیگار و حرکت خاکستر واضح بود؛ بعداً در مصاحبه پذیرفت.',
    aiVerdict: 'likely_violation',
    aiConfidence: 0.88,
    evidenceFrames: [
      {
        id: 'ef-017-a',
        label: 'فریم الف',
        timestamp: T(-70, 0),
        caption: 'سیگار زیر سایبان روشن شد',
      },
      {
        id: 'ef-017-b',
        label: 'فریم ب',
        timestamp: T(-70, 1),
        caption: 'تکان خاکستر به سمت باغچه',
      },
      {
        id: 'ef-017-c',
        label: 'فریم ج',
        timestamp: T(-69, 50),
        caption: 'پیش از رسیدن حراست خاموش شد',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-017-1',
        at: T(-70, 1),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'زون ممنوع سیگار — اطمینان بالا',
      },
      {
        id: 'dl-017-2',
        at: T(-69, 0),
        actor: 'مرتضی بل',
        action: 'acknowledge',
        note: 'حراست مطلع شد',
      },
      {
        id: 'dl-017-3',
        at: T(-65, 0),
        actor: 'جمشید احمدی',
        action: 'confirm',
        note: 'کارگر شناسایی شد — اخطار کتبی',
      },
      {
        id: 'dl-017-4',
        at: T(-60, 0),
        actor: 'جمشید احمدی',
        action: 'close',
        note: 'با سابقه پیمانکار بسته شد',
      },
    ],
    correctiveActions: [
      {
        id: 'ca-017-1',
        title: 'نصب مجدد تابلوی ممنوعیت سیگار در سایبان غرب',
        owner: 'مرتضی بل',
        dueDate: '2026-08-07',
        status: 'done',
      },
    ],
    falsePositive: false,
  },
  {
    id: 'inc-018',
    code: 'INC-2026-0809-018',
    title: 'نبود همزمان جلیقه و عینک — لبه عرشه',
    projectId: 'proj-nht-p2',
    zoneId: 'zone-02',
    cameraId: 'cam-01',
    ruleId: 'rule-01',
    contractorId: 'ctr-03',
    severity: 'high',
    status: 'escalated',
    confidence: 0.9,
    detectedAt: T(-0.15, 10),
    updatedAt: T(-0.05, 0),
    assignee: 'جمشید احمدی',
    aiSummary:
      'کارگر هاربرفرم بدون جلیقه بازتابی یا عینک ایمنی هنگام فرود فعال فولاد به لبه عرشه شمال نزدیک شد. کلاه‌ایمنی داشت. دومین رویداد بحرانی همین زون در این شیفت.',
    aiVerdict: 'likely_violation',
    aiConfidence: 0.91,
    evidenceFrames: [
      {
        id: 'ef-018-a',
        label: 'فریم الف',
        timestamp: T(-0.15, 10),
        caption: 'کارگر بدون جلیقه به لبه نزدیک می‌شود',
      },
      {
        id: 'ef-018-b',
        label: 'فریم ب',
        timestamp: T(-0.15, 11),
        caption: 'بدون حفاظت چشم؛ فرود فولاد نزدیک است',
      },
      {
        id: 'ef-018-c',
        label: 'فریم ج',
        timestamp: T(-0.15, 12),
        caption: 'ناظر بار سیگنال توقف می‌دهد',
      },
      {
        id: 'ef-018-d',
        label: 'فریم د',
        timestamp: T(-0.1, 0),
        caption: 'مسیر ارجاع به مسئول ایمنی باز شد',
      },
    ],
    clipPlaceholder: CLIP,
    decisionLog: [
      {
        id: 'dl-018-1',
        at: T(-0.15, 11),
        actor: 'سامانه',
        action: 'ai_verify',
        note: 'نبود چندکلاسه تجهیزات حفاظت فردی نزدیک لبه فعال',
      },
      {
        id: 'dl-018-2',
        at: T(-0.1, 30),
        actor: 'مرتضی بل',
        action: 'acknowledge',
        note: 'کارگر فوراً از لبه خارج شد',
      },
      {
        id: 'dl-018-3',
        at: T(-0.08, 0),
        actor: 'جمشید احمدی',
        action: 'confirm',
        note: 'شکست دوگانه تجهیزات حفاظت فردی تأیید شد',
      },
      {
        id: 'dl-018-4',
        at: T(-0.05, 0),
        actor: 'النا رضایی',
        action: 'escalate',
        note: 'ارجاع شد — ریسک تکراری زون در این شیفت',
      },
    ],
    correctiveActions: [
      {
        id: 'ca-018-1',
        title: 'توقف کار تیم عرشه هاربرفرم — ممیزی تجهیزات حفاظت فردی',
        owner: 'بتن هاربرفرم',
        dueDate: '2026-08-09',
        status: 'in_progress',
      },
    ],
    falsePositive: false,
  },
]

export const HSE_ALERT_LOGS: AlertLogEntry[] = [
  {
    id: 'al-01',
    at: T(-2, 9),
    channel: 'telegram',
    severity: 'critical',
    target: 'گفتگوی عملیات ایمنی ***4821',
    incidentCode: 'INC-2026-0809-001',
    result: 'sent',
    detail: 'نقض ممنوع بحرانی با پیوند عمیق به حادثه ارسال شد',
  },
  {
    id: 'al-02',
    at: T(-2, 10),
    channel: 'email',
    severity: 'critical',
    target: 'ایمنی@نمونه.ایران',
    incidentCode: 'INC-2026-0809-001',
    result: 'sent',
    detail: 'خلاصه ایمیل با تصاویر کوچک شواهد',
  },
  {
    id: 'al-03',
    at: T(-1, 6),
    channel: 'telegram',
    severity: 'critical',
    target: 'گفتگوی عملیات ایمنی ***4821',
    incidentCode: 'INC-2026-0809-003',
    result: 'sent',
    detail: 'هشدار بحرانی نزدیکی خودرو',
  },
  {
    id: 'al-04',
    at: T(-0.8, 16),
    channel: 'telegram',
    severity: 'high',
    target: 'گفتگوی عملیات ایمنی ***4821',
    incidentCode: 'INC-2026-0809-005',
    result: 'sent',
    detail: 'هشدار شدت بالای کلاه‌ایمنی',
  },
  {
    id: 'al-05',
    at: T(-0.25, 41),
    channel: 'telegram',
    severity: 'high',
    target: 'گفتگوی عملیات ایمنی ***4821',
    incidentCode: 'INC-2026-0809-006',
    result: 'queued',
    detail: 'در صف — محدودیت نرخ گفتگو',
  },
  {
    id: 'al-06',
    at: T(-0.15, 12),
    channel: 'telegram',
    severity: 'high',
    target: 'گفتگوی عملیات ایمنی ***4821',
    incidentCode: 'INC-2026-0809-018',
    result: 'sent',
    detail: 'اعلان ارجاع تجهیزات حفاظت فردی زون تکراری',
  },
  {
    id: 'al-07',
    at: T(-0.15, 13),
    channel: 'webhook',
    severity: 'high',
    target: 'https://hooks.sitepilot.local/hse/incidents',
    incidentCode: 'INC-2026-0809-018',
    result: 'sent',
    detail: 'بسته وب‌هوک پذیرفته شد (۲۰۲)',
  },
  {
    id: 'al-08',
    at: T(-6, 41),
    channel: 'email',
    severity: 'high',
    target: 'ناظر@نمونه.ایران',
    incidentCode: 'INC-2026-0809-012',
    result: 'sent',
    detail: 'اعلان فاصله نگهبان آتش کار گرم',
  },
  {
    id: 'al-09',
    at: T(-18, 32),
    channel: 'webhook',
    severity: 'high',
    target: 'https://hooks.sitepilot.local/hse/incidents',
    incidentCode: 'INC-2026-0808-014',
    result: 'failed',
    detail: 'مهلت پس از ۸ ثانیه — گیرنده در دسترس نبود',
  },
  {
    id: 'al-10',
    at: T(-5, 23),
    channel: 'telegram',
    severity: 'critical',
    target: 'گفتگوی عملیات ایمنی ***4821',
    incidentCode: 'INC-2026-0809-002',
    result: 'sent',
    detail: 'هشدار بحرانی خطر سقوط',
  },
  {
    id: 'al-11',
    at: T(-3, 46),
    channel: 'email',
    severity: 'medium',
    target: 'ایمنی@نمونه.ایران',
    incidentCode: 'INC-2026-0809-008',
    result: 'sent',
    detail: 'هشدار متوسط سیگار (فقط ایمیل طبق مسیریابی)',
  },
  {
    id: 'al-12',
    at: T(-0.4, 6),
    channel: 'email',
    severity: 'medium',
    target: 'ناظر@نمونه.ایران',
    incidentCode: 'INC-2026-0809-014',
    result: 'sent',
    detail: 'فاصله تخته داربست — ایمیل ناظر',
  },
]

export const HSE_ALERT_ROUTING: AlertRouting[] = [
  { severity: 'critical', telegram: true, email: true, webhook: true },
  { severity: 'high', telegram: true, email: true, webhook: true },
  { severity: 'medium', telegram: false, email: true, webhook: false },
  { severity: 'low', telegram: false, email: false, webhook: false },
]

export const HSE_TELEGRAM_SETTINGS = {
  botConfigured: true,
  chatIdMasked: '***4821',
  notifyCritical: true,
  notifyHigh: true,
  notifyMedium: false,
}

const OPEN_STATUSES = new Set([
  'new',
  'acknowledged',
  'ai_review',
  'confirmed',
  'escalated',
  'assigned',
])

export function getOverviewKpis(): OverviewKpis {
  const incidents = HSE_INCIDENTS
  const cameras = HSE_CAMERAS
  const activeIncidents = incidents.filter((i) => OPEN_STATUSES.has(i.status)).length
  const confirmedViolations = incidents.filter(
    (i) => (i.status === 'confirmed' || i.status === 'closed' || i.status === 'escalated') && !i.falsePositive,
  ).length
  const falsePositives = incidents.filter((i) => i.falsePositive).length
  const camerasOnline = cameras.filter((c) => c.health === 'online').length

  return {
    totalIncidents: incidents.length,
    activeIncidents,
    confirmedViolations,
    falsePositives,
    avgAckMinutes: 6.4,
    avgCloseHours: 9.2,
    camerasOnline,
    camerasTotal: cameras.length,
  }
}

export function getIncidentById(id: string): HseIncident | undefined {
  return HSE_INCIDENTS.find((i) => i.id === id)
}

export function getZone(id: string): HseZone | undefined {
  return HSE_ZONES.find((z) => z.id === id)
}

export function getCamera(id: string): HseCamera | undefined {
  return HSE_CAMERAS.find((c) => c.id === id)
}

export function getRule(id: string): HseRule | undefined {
  return HSE_RULES.find((r) => r.id === id)
}

export function getContractor(id: string): HseContractor | undefined {
  return HSE_CONTRACTORS.find((c) => c.id === id)
}

export function severityBreakdown(): Record<Severity, number> {
  const counts: Record<Severity, number> = {
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
  }
  for (const incident of HSE_INCIDENTS) {
    counts[incident.severity] += 1
  }
  return counts
}

export function topRiskZones(): Array<{ zoneId: string; name: string; count: number }> {
  const byZone = new Map<string, number>()
  for (const incident of HSE_INCIDENTS) {
    byZone.set(incident.zoneId, (byZone.get(incident.zoneId) ?? 0) + 1)
  }
  return [...byZone.entries()]
    .map(([zoneId, count]) => ({
      zoneId,
      name: getZone(zoneId)?.name ?? zoneId,
      count,
    }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 5)
}

export function contractorComparison(): HseContractor[] {
  return [...HSE_CONTRACTORS].sort(
    (a, b) => b.openIncidents + b.confirmedViolations - (a.openIncidents + a.confirmedViolations),
  )
}

export function recentCritical(limit: number): HseIncident[] {
  return [...HSE_INCIDENTS]
    .filter((i) => i.severity === 'critical' || i.severity === 'high')
    .sort((a, b) => +new Date(b.detectedAt) - +new Date(a.detectedAt))
    .slice(0, limit)
}

export function cameraHealthSummary(): Record<string, number> {
  const summary: Record<string, number> = {
    online: 0,
    degraded: 0,
    offline: 0,
    calibrating: 0,
  }
  for (const camera of HSE_CAMERAS) {
    summary[camera.health] = (summary[camera.health] ?? 0) + 1
  }
  return summary
}
